### ISSUE TITLE
is_docker_available uninformative error

### ISSUE THREAD

**Issue by rasmus87** [ropensci/outsider.base#1]
If docker.base:::is_docker_available() is run and the ssh package in R is not installed it just returns FALSE.

I found this issue, since when I loaded outsider it kept returning:
```
> library(outsider)
Docker is not installed. Follow the installation instructions for your system:
https://docs.docker.com/
----------------
outsider v 0.1.1
----------------
```

docker was installed, the problem was that the ssh package was not installed.

**Comment by DomBennett** [comment]
Fixed with new `with_ssh` arg.
